name: Build 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (dev/release)'
        required: true
        default: 'dev'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11.0.11'
          distribution: 'liberica'
          java-package: 'jdk+fx"
      - name: Make artifact
        run: ./gradlew build
